language: node_js
node_js:
  - '0.8'
  - '0.10'
  - '0.11'
  - 'iojs-v1.0'
  - 'iojs-v1.1'

sudo: false

before_install:
- npm install -g npm@1.4.6

script:
- npm test
- npm run coverage-tests

matrix:
  allow_failures:
  - node_js: "0.11"
